### ISSUE TITLE
Criar o model para Contact, aplicar as relações e factories para gerar 15 users com os seus contactos

### ISSUE THREAD

**Issue by limasoft-dev** [limasoft-dev/relationships#2]
# Todo
- [x] Create Model Contact -mf
- Phone
- Address
- [x] Define migration fields
- [x] Define Models fillables and relationships
- [x] Define Factory
- [x] Define database seeder
- [x] Run migrate fresh with seed sucessfully
